export const MOVE_ONE = 'MOVE_ONE'
export const MOVE_TWO = 'MOVE_TWO'
export const MOVE_THREE = 'MOVE_THREE'
export const BACK_UP = 'BACK_UP'
export const ROTATE_RIGHT = 'ROTATE_RIGHT'
export const ROTATE_LEFT = 'ROTATE_LEFT'
export const U_TURN = 'U_TURN'

export const NORTH = 'NORTH'
export const EAST = 'EAST'
export const SOUTH = 'SOUTH'
export const WEST = 'WEST'

export const PLAIN = 'PLAIN'
export const FLAG = 'FLAG'
export const HOLE = 'HOLE'
